= Security and Functional Flaw Reporting
:page-toclevels: 4

:PGPREL: https://download.strongswan.org/STRONGSWAN-RELEASE-PGP-KEY
:ADV:    https://strongswan.org/security/
:FIXES:  https://download.strongswan.org/security/
:GITHUB: https://github.com/strongswan/strongswan


== Security Flaws

=== Reporting

* Please follow {GITHUB}/security/policy[our security policy] if you find or
  suspect a security-relevant flaw in strongSwan.

=== List of Published and Fixed Security Flaws

 * A list of all published strongSwan high and medium security flaws
   can be found {ADV}[on our website], as can the corresponding
   {FIXES}[security patches and OSV files]. Each security patch is signed by the
   {PGPREL}[strongSwan release PGP key].

== Functional Flaws

 * Please report all non-security-related flaws and bugs by opening a
   {GITHUB}/issues[*new issue*] on our {GITHUB}/issues[strongSwan GitHub site].
   Of course it is helpful if you can already pinpoint the code file where you
   suspect the bug or in the case of a crash to provide a backtrack analysis of
   the core dump.

 * User patches fixing flaws are always welcome can be posted as a
   {GITHUB}/pulls[*pull request*] on our {GITHUB}/pulls[strongSwan GitHub site].
